# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: minitwitter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'minitwitter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11minitwitter.proto\"2\n\x13RegisterUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"/\n\x10LoginUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"/\n\x0eMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"#\n\x12GetMessagesRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\"$\n\x10MessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2\xcb\x01\n\x0bMiniTwitter\x12/\n\x0cregisterUser\x12\x14.RegisterUserRequest\x1a\t.Response\x12)\n\tloginUser\x12\x11.LoginUserRequest\x1a\t.Response\x12)\n\x0bsendMessage\x12\x0f.MessageRequest\x1a\t.Response\x12\x35\n\x0bgetMessages\x12\x13.GetMessagesRequest\x1a\x11.MessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minitwitter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERUSERREQUEST']._serialized_start=21
  _globals['_REGISTERUSERREQUEST']._serialized_end=71
  _globals['_LOGINUSERREQUEST']._serialized_start=73
  _globals['_LOGINUSERREQUEST']._serialized_end=120
  _globals['_MESSAGEREQUEST']._serialized_start=122
  _globals['_MESSAGEREQUEST']._serialized_end=169
  _globals['_GETMESSAGESREQUEST']._serialized_start=171
  _globals['_GETMESSAGESREQUEST']._serialized_end=206
  _globals['_RESPONSE']._serialized_start=208
  _globals['_RESPONSE']._serialized_end=234
  _globals['_MESSAGESRESPONSE']._serialized_start=236
  _globals['_MESSAGESRESPONSE']._serialized_end=272
  _globals['_MINITWITTER']._serialized_start=275
  _globals['_MINITWITTER']._serialized_end=478
# @@protoc_insertion_point(module_scope)
