# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: minitwitter.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'minitwitter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11minitwitter.proto\"!\n\x0eMessageRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"#\n\x12GetMessagesRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\"$\n\x10MessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2o\n\x0bMiniTwitter\x12)\n\x0bsendMessage\x12\x0f.MessageRequest\x1a\t.Response\x12\x35\n\x0bgetMessages\x12\x13.GetMessagesRequest\x1a\x11.MessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minitwitter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=21
  _globals['_MESSAGEREQUEST']._serialized_end=54
  _globals['_GETMESSAGESREQUEST']._serialized_start=56
  _globals['_GETMESSAGESREQUEST']._serialized_end=91
  _globals['_RESPONSE']._serialized_start=93
  _globals['_RESPONSE']._serialized_end=119
  _globals['_MESSAGESRESPONSE']._serialized_start=121
  _globals['_MESSAGESRESPONSE']._serialized_end=157
  _globals['_MINITWITTER']._serialized_start=159
  _globals['_MINITWITTER']._serialized_end=270
# @@protoc_insertion_point(module_scope)
